#!/usr/bin/env python3
"""Build src/js/sprites.js: embeds cut sprites as base64 data-URIs + manifest.

The game opens as a plain file (file://), which blocks fetch()/CORS, so the
renderer gets images as data URIs in an ES module — zero server needed.

Usage: python3 scripts/build_sprites_js.py
Reads:  assets/sprites/sprites.json + assets/sprites/*.png
Writes: src/js/sprites.js  (exports SPRITES manifest + an images map)
"""
import base64, json
from pathlib import Path

ROOT = Path.home() / "jura-defense"
SPR = ROOT / "assets/sprites"
OUT = ROOT / "src/js/sprites.js"

manifest = json.load(open(SPR / "sprites.json"))

def data_uri(png_path):
    return "data:image/png;base64," + base64.b64encode(png_path.read_bytes()).decode()

lines = []
lines.append("// Auto-generated by scripts/build_sprites_js.py — do not edit by hand.")
lines.append("// Embeds cut sprite PNGs as data URIs so the game works from file://.")
lines.append("")
lines.append("export const SPRITES = " + json.dumps(manifest, indent=2) + ";")
lines.append("")
lines.append("// Lazy image cache keyed by sprite id.")
lines.append("const _imgs = {};")
lines.append("export function spriteImage(id, onload) {")
lines.append("  if (typeof Image === 'undefined') return null;  // Node/sim context: no browser Image")
lines.append("  if (_imgs[id]) { if (onload) { const i = _imgs[id]; if (i.complete) onload(i); else i.addEventListener('load', () => onload(i)); } return _imgs[id]; }")
lines.append("  const img = new Image(); _imgs[id] = img;")
lines.append("  const m = SPRITES[id];")
lines.append("  img.src = IMAGES[id];")
lines.append("  if (onload) img.addEventListener('load', () => onload(img));")
lines.append("  return img;")
lines.append("}")
lines.append("")
lines.append("export const IMAGES = {")
for pid, meta in manifest.items():
    png = SPR / meta["file"]
    if png.exists():
        lines.append(f'  "{pid}": "{data_uri(png)}",')
lines.append("};")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB), {len(manifest)} sprites embedded")